# Generated by Django 3.2.9 on 2021-11-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, choices=[('K', 'Казань'), ('M', 'Москва'), ('S', 'Санкт-Петербург')], max_length=1, null=True),
        ),
    ]
